### ISSUE TITLE
[Proposal] leverage react-ga

### ISSUE THREAD

**Issue by seraphjiang** [BionIT/google-analytics-plugin#3]
there is popular react module which wrap the ga for react app.

https://github.com/react-ga/react-ga

i had a try , it works

https://github.com/seraphjiang/osd-ga/blob/main/public/hacks.js

**Comment by BionIT** [comment]
react-ga only supports Universal Analytics(I am using GA4 id) and UA is going away https://support.google.com/analytics/answer/11583528, there is another npm module called react-ga4 which supports GA4 and local test was successful. The reason I didn't use react-ga4 for the first place is because it doesn't have updates since end of last year. Do we want to use react-ga4 instead?
